from typing import Literal, Optional, Sequence, Tuple, Union

BytesLike = Union[bytes, bytearray, memoryview]
EncodedFormat = Literal["wav", "flac", "mp3", "vorbis", "opus", "aac", "m4a", "mp4"]
PcmTuple = Tuple[int, int, list[float]]

class StreamDecoder:
    def __init__(self) -> None: ...
    def decode_stream(self, chunk: BytesLike) -> Optional[PcmTuple]: ...
    def reset(self) -> None: ...
    def buffered_len(self) -> int: ...

def detect_format(input: BytesLike) -> Optional[str]: ...

def decode_audio(input: BytesLike) -> PcmTuple: ...

def decode_wav(input: BytesLike) -> PcmTuple: ...

def decode_flac(input: BytesLike) -> PcmTuple: ...

def decode_mp3(input: BytesLike) -> PcmTuple: ...

def decode_vorbis(input: BytesLike) -> PcmTuple: ...

def decode_opus(input: BytesLike) -> PcmTuple: ...

def decode_aac(input: BytesLike) -> PcmTuple: ...

def decode_m4a(input: BytesLike) -> PcmTuple: ...

def encode_audio(
    format: EncodedFormat,
    sample_rate: int,
    channels: int,
    samples: Sequence[float],
) -> bytes: ...

def encode_audio_production(
    format: EncodedFormat,
    sample_rate: int,
    channels: int,
    samples: Sequence[float],
) -> bytes: ...

def encode_wav(sample_rate: int, channels: int, samples: Sequence[float]) -> bytes: ...

def encode_flac(sample_rate: int, channels: int, samples: Sequence[float]) -> bytes: ...

def encode_mp3(sample_rate: int, channels: int, samples: Sequence[float]) -> bytes: ...

def encode_vorbis(sample_rate: int, channels: int, samples: Sequence[float]) -> bytes: ...

def encode_opus(sample_rate: int, channels: int, samples: Sequence[float]) -> bytes: ...

def encode_aac(sample_rate: int, channels: int, samples: Sequence[float]) -> bytes: ...

def encode_m4a(sample_rate: int, channels: int, samples: Sequence[float]) -> bytes: ...

def demux_m4a_as_aac_adts(input: BytesLike) -> bytes: ...
